language: python
python:
  - "3.8"
jobs:
  include:
    - name: "Ubuntu Focal Fossa 20.04 LTS"
      os: linux
      dist: focal
    - name: "Ubuntu Bionic Beaver 18.04 LTS"
      os: linux
      dist: bionic
    - name: "Ubuntu Xenial Xerus 16.04 LTS"
      os: linux
      dist: xenial
    - name: "FreeBSD 12.1"
      os: freebsd
    - name: "macOS Big Sur 11"
      os: osx
      osx_image: xcode12.5
      language: shell
      before_install:
        - brew install python3
    - name: "macOS Catalina 10.15"
      os: osx
      osx_image: xcode12
      language: shell
      before_install:
        - brew install python3
    - name: "macOS Mojave 10.14"
      os: osx
      osx_image: xcode11.3
      language: shell
      before_install:
        - brew install python3
    - name: "Windows Server 1809"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -r REQUIREMENTS
script: pytest
